default: &defaults
  # Your push api key, it is possible to set this dynamically using ERB:
  # push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  push_api_key: 'ee5237aa-38e9-4ab7-8ee0-12bd645ecfe9'
  name: 'CCCA'

development:
  <<: *defaults
  active: false
  debug: true

staging:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
