defaults: &defaults
  fog_directory:  "<%= ENV['FOG_DIRECTORY'] %>"
  fog_provider: "<%= ENV['FOG_PROVIDER'] %>"
  aws_access_key_id:  "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  # manifest: true
  # custom_headers: { '.*' => { cache_control: 'private, max-age=315576000', expires:  "<%= 1.year.from_now.httpdate %>"} }
  # Invalidate a file on a cdn after uploading files
  # config.cdn_distribution_id = "12345"
  # config.invalidate = ['file1.js']

  # Increase upload performance by configuring your region
  fog_region:  "<%=  ENV['FOG_REGION'] %>"
  #
  # Don't delete files from the store
  # config.existing_remote_files = "delete"
  #
  # Automatically replace files with their equivalent gzip compressed version
  gzip_compression: true

test:
  <<: *defaults
  enabled: false

development:
  <<: *defaults
  enabled: false

staging:
  <<: *defaults

production:
  <<: *defaults